<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/F5_Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('covid_toy.csv')

In [ ]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
print("Shape:", df.shape)

Shape: (100, 6)


In [ ]:
print("\nColumns:\n", df.columns)


Columns:
 Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')


In [ ]:
print("\nInfo:")
print(df.info())


Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB
None


In [ ]:
print(df.describe())


              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000


In [ ]:
print(df.isnull().sum())


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64


In [ ]:
for col in df.select_dtypes(include='object').columns:
    print(f"\n{col} unique values:")
    print(df[col].value_counts())



gender unique values:
gender
Female    59
Male      41
Name: count, dtype: int64

cough unique values:
cough
Mild      62
Strong    38
Name: count, dtype: int64

city unique values:
city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

has_covid unique values:
has_covid
No     55
Yes    45
Name: count, dtype: int64


In [ ]:
from re import X
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [ ]:
from sklearn.impute import SimpleImputer

si = SimpleImputer(strategy='mean')

X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.transform(X_test[['fever']])


In [ ]:
X_train

age  gender  fever   cough       city
62   56  Female  104.0  Strong  Bangalore
64   42    Male  104.0    Mild     Mumbai
81   65    Male   99.0    Mild      Delhi
30   15    Male  101.0    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
71   75  Female  104.0  Strong      Delhi
29   34  Female    NaN  Strong     Mumbai
42   27    Male  100.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
56   71    Male    NaN  Strong    Kolkata

[80 rows x 5 columns]

In [ ]:
X_train_fever

array([[104.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [ 98.        ],
       [100.97183099],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [100.97183099],
       [104.        ],
       [101.        ],
       [100.        ],
       [103.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [102.        ],
       [102.        ],
       [ 99.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [ 99.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [ 99

In [ ]:
X_train_fever.shape

(80, 1)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])


In [ ]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
import pandas as pd


In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [ ]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

In [ ]:
X_train_age

array([[56],
       [42],
       [65],
       [15],
       [60],
       [19],
       [12],
       [82],
       [49],
       [69],
       [47],
       [69],
       [72],
       [13],
       [84],
       [51],
       [19],
       [55],
       [50],
       [47],
       [81],
       [34],
       [26],
       [66],
       [49],
       [19],
       [69],
       [74],
       [22],
       [71],
       [48],
       [16],
       [42],
       [80],
       [18],
       [54],
       [73],
       [49],
       [16],
       [24],
       [33],
       [ 8],
       [19],
       [59],
       [25],
       [14],
       [65],
       [83],
       [27],
       [38],
       [12],
       [38],
       [11],
       [10],
       [23],
       [80],
       [20],
       [34],
       [60],
       [79],
       [64],
       [75],
       [10],
       [20],
       [34],
       [82],
       [44],
       [83],
       [46],
       [11],
       [ 5],
       [82],
       [20],
       [65],
       [70],
       [75],
       [34],

In [ ]:
X_train_age.shape

(80, 1)

In [ ]:
import numpy as np
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [ ]:
X_train_transformed.shape

(80, 7)

In [ ]:
X_train_transformed

array([[ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 100.97183099,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        , 101.        ,   0.        ,   1.        ,
          0.    

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(strategy='mean'), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender','city'])
], remainder='passthrough')


In [ ]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

print("Before:", X_train.shape)
print("After:", X_train_transformed.shape)


Before: (80, 5)
After: (80, 7)
