<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/Practise_2(NumPy_Indexing_and_Slicing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Creating an Array

In [1]:
import numpy as np

In [7]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


#2. Accessing Single Element (Positive Index)

In [8]:
print(arr[0])

10


In [9]:
print(arr[1])

20


#3. Negative Indexing

In [10]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[-1])
print(arr[-2])
print(arr[-5])

50
40
10


#4. Updating an Element

In [13]:
arr[1]=30
print(arr)

[10 30 30 40 50]


#5. Basic Slicing

In [14]:
import numpy as np

arr=np.array([10,20,30,40,50,60,70])

print(arr[1:5])

[20 30 40 50]


#6. Slice from Beginning

In [15]:
print(arr[:-1])

[10 20 30 40 50 60]


In [16]:
print(arr[-1:])

[70]


In [17]:
print(arr[:1])

[10]


#7. Entire Array

In [18]:
import numpy as np

arr=np.array([10,20,30,40,50])

print(arr[:])

[10 20 30 40 50]


#8. Slicing with Step

In [19]:
import numpy as np

arr=np.array([10,20,30,40,50,60,70])

print(arr[::2])

[10 30 50 70]


#9. Reverse Array

In [20]:
print(arr[::-1])

[70 60 50 40 30 20 10]


#10. Reverse with Step

In [21]:
import numpy as np

arr=np.array([10,20,30,40,50,60])

print(arr[::-2])

[60 40 20]


#11. 2D Array Indexing

In [22]:
import numpy as np

arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
print(arr[1,2])

60


In [25]:
print(arr[0,0])
print(arr[0,1])
print(arr[1,2])
print(arr[2,1])

10
20
60
80


#12. Access Entire Row

In [26]:
import numpy as np

arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(arr[0])
print(arr[2])

[10 20 30]
[70 80 90]


In [28]:
print(arr[1])

[40 50 60]


#13. Access Entire Column

In [29]:
import numpy as np

arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(arr[:,0])
print(arr[:,2])

[10 40 70]
[30 60 90]


In [30]:
print(arr[:,1])

[20 50 80]


#14. Row Slicing

In [31]:
print(arr[0:2])

[[10 20 30]
 [40 50 60]]


#15. Column Slicing

In [32]:
print(arr[:,0:2])

[[10 20]
 [40 50]
 [70 80]]


#16. Extract Sub Matrix

In [33]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


#17. Modify Multiple Elements

In [34]:
arr[1:4]=100
print(arr)

[[ 10  20  30]
 [100 100 100]
 [100 100 100]]


#19. Modify Row

In [35]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

arr[1]=[100,200,300]

print(arr)

[[  1   2   3]
 [100 200 300]
 [  7   8   9]]


#20. Modify Column

In [36]:
arr[:,1]=0
print(arr)

[[  1   0   3]
 [100   0 300]
 [  7   0   9]]


#21. Multiple Row and Column Selection

In [37]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(arr[[0,2],[1,2]])

[2 9]


#22. Find Elements Greater than 50

In [38]:
result=arr[arr>5]
print(result)

[6 7 8 9]


# #23. Extract Diagonal

In [39]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.diag(arr))

[1 5 9]


#Practical Example: Student Marks

In [40]:
import numpy as np

marks=np.array([[80,75,90],
                [60,70,65],
                [95,85,92],
                [55,68,72]])

print("Marks Matrix")
print(marks)

print("\nFirst Student")
print(marks[0])

print("\nSecond Subject")
print(marks[:,1])

print("\nTop Two Students")
print(marks[:2])

print("\nStudents Scoring Above 80")
print(marks[marks>80])

Marks Matrix
[[80 75 90]
 [60 70 65]
 [95 85 92]
 [55 68 72]]

First Student
[80 75 90]

Second Subject
[75 70 85 68]

Top Two Students
[[80 75 90]
 [60 70 65]]

Students Scoring Above 80
[90 95 85 92]
