<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/Practise_Day_4(Numpy_Joining_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. concatenate()

In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

result=np.concatenate((arr1,arr2))
print(result)


[ 1  2  3  4  5  6  7  8  9 10]


2D Arrays (Row Wise)

In [3]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])

c=np.concatenate((a,b),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Column Wise

In [4]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])

c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


#2. stack()

In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.stack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

result = np.stack((a,b), axis=1)

print(result)

[[1 4]
 [2 5]
 [3 6]]


#3. vstack()

In [8]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np

a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6]])

result = np.vstack((a,b))

print(result)

[[1 2]
 [3 4]
 [5 6]]


#4. hstack()

In [11]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [12]:
import numpy as np

a = np.array([[1,2],
              [3,4]])

b = np.array([[5],
              [6]])

result = np.hstack((a,b))

print(result)

[[1 2 5]
 [3 4 6]]


#Multiple Columns

In [13]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

c = np.array([7,8,9])

result = np.column_stack((a,b,c))

print(result)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#7. row_stack()

In [14]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

result = np.row_stack((a,b))

print(result)

[[1 2 3]
 [4 5 6]]


/tmp/ipykernel_5163/3035176782.py:7: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result = np.row_stack((a,b))


#8. block()

In [15]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

result = np.block([[A,B]])

print(result)

[[1 2 5 6]
 [3 4 7 8]]


#Practical Program 1: Join Two Student Marks

In [17]:
import numpy as np

student1 = np.array([80,85,90])

student2 = np.array([75,88,92])

all_marks = np.concatenate((student1,student2))

print(all_marks)

[80 85 90 75 88 92]


#Practical Program 2: Combine Two Classes

In [18]:
import numpy as np

classA = np.array([[80,90],
                   [75,88]])

classB = np.array([[92,95],
                   [78,84]])

all_students = np.vstack((classA,classB))

print(all_students)

[[80 90]
 [75 88]
 [92 95]
 [78 84]]


#Practical Program 3: Merge Employee Data

In [19]:
import numpy as np

ids = np.array([101,102,103])

salary = np.array([45000,50000,55000])

employee = np.column_stack((ids,salary))

print(employee)

[[  101 45000]
 [  102 50000]
 [  103 55000]]
