## Understanding NumPy

**NumPy (Numerical Python)** is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. It is the cornerstone of the Python data science ecosystem, serving as the basis for libraries like Pandas, SciPy, and Scikit-learn.

### Core Features and Concepts:

1.  **`ndarray` (N-dimensional Array) Object:**
    *   The central object in NumPy is the `ndarray`, which is a powerful N-dimensional array object. It's a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
    *   Unlike Python lists, NumPy arrays are designed to store homogeneous data types, leading to more efficient storage and operations.

2.  **Performance:**
    *   NumPy operations are implemented in C and Fortran, making them significantly faster than equivalent operations on standard Python lists, especially for large datasets.
    *   This efficiency comes from its memory management; `ndarray`s store data in a contiguous block of memory, allowing for optimized vectorized operations.

3.  **Vectorization:**
    *   NumPy encourages writing code using array-based operations (vectorization) instead of explicit loops. This not only makes code more concise and readable but also leverages NumPy's optimized C implementations for dramatic speed improvements.
    *   Example: `arr1 + arr2` performs element-wise addition on two arrays without needing a `for` loop.

4.  **Broadcasting:**
    *   NumPy's broadcasting mechanism allows arithmetic operations between arrays of different shapes. It automatically "stretches" smaller arrays to match the shape of larger arrays, provided they are compatible.
    *   This eliminates the need for explicit tiling or duplication of arrays, saving memory and improving performance.

5.  **Mathematical Functions:**
    *   NumPy provides a vast collection of mathematical functions that operate element-wise on arrays, including:
        *   **Trigonometric:** `sin()`, `cos()`, `tan()`, etc.
        *   **Exponents and Logarithms:** `exp()`, `log()`, `log10()`, etc.
        *   **Rounding:** `floor()`, `ceil()`, `round()`.
        *   **Statistical:** `mean()`, `median()`, `std()`, `sum()`, `max()`, `min()`.
        *   **Linear Algebra:** Dot products, matrix multiplication, determinants, inverses, eigenvalues, etc.

### Why Use NumPy?

*   **Efficiency:** Faster computation on large datasets compared to Python lists.
*   **Memory Efficiency:** Arrays consume less memory than Python lists for storing numerical data.
*   **Convenience:** Rich set of functions for array manipulation and mathematical operations.
*   **Foundation:** Forms the basis for many other scientific computing libraries in Python.

### Basic Array Creation and Manipulation:

```python
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3])                 # 1D array
arr2 = np.array([[1, 2], [3, 4]])         # 2D array
arr_zeros = np.zeros((3, 4))              # Array of zeros
arr_ones = np.ones((2, 2))                # Array of ones
arr_range = np.arange(0, 10, 2)           # Array with a range of values
arr_linspace = np.linspace(0, 1, 5)       # Array with evenly spaced values

# Array attributes
print(f"Shape of arr2: {arr2.shape}")        # (rows, columns)
print(f"Dimensions of arr2: {arr2.ndim}")     # Number of dimensions
print(f"Data type of arr2: {arr2.dtype}")    # Data type of elements
print(f"Size of arr2: {arr2.size}")        # Total number of elements

# Array operations
addition = arr1 + arr1
multiplication = arr1 * 2
matrix_mult = np.dot(arr2, arr2) # Matrix multiplication

# Indexing and Slicing
print(arr1[0])          # First element
print(arr2[0, 1])       # Element at row 0, column 1
print(arr1[1:])         # Slice from second element to end
print(arr2[:, 0])       # All rows, first column

# Reshaping
arr_reshaped = np.arange(9).reshape(3, 3)
print(f"Reshaped array:\n{arr_reshaped}")
```

In summary, NumPy is an indispensable library for anyone working with numerical data in Python, providing a robust and efficient framework for array computing.

#Unit 2: Creating Arrays

#1. 1D-Array

In [2]:
import numpy as np
a=np.array(['1','2','3'])
print(a)

['1' '2' '3']


In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array(['f','a','i','s','a','L'])
print(b)

['f' 'a' 'i' 's' 'a' 'L']


2.np.arange()

In [6]:
var='Aaliya Fatma'
arr=np.arange(1,10)
print(arr)
print(var)

[1 2 3 4 5 6 7 8 9]
Aaliya Fatma


In [7]:
arr2=np.arange(1,20,2,dtype=np.float32)
print(arr2)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


3.np.linspace()

In [8]:
arr=np.linspace(1,45,3)
print(arr)

[ 1. 23. 45.]


4. Using np.zeros()

In [10]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


5. Using np.ones()

In [11]:
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


6. Using np.empty()

In [12]:
arr=np.empty(5)
print(arr)

[3.20000076e+01 3.27680079e+04 1.04857625e+06 1.67772201e+07
 1.00663312e+08]


7. Using np.full()

In [14]:
arr=np.full(5,100)
print(arr)

[100 100 100 100 100]


8. Using np.random.rand()

In [16]:
arr=np.random.rand(5)
print(arr)

[0.80067842 0.363788   0.362489   0.04291399 0.15392363]


9. Using np.random.randint()

In [17]:
arr=np.random.randint(1,100,5)
print(arr)

[67 26 34 19 94]


10. Using np.random.uniform()

In [18]:
arr=np.random.uniform(1,100,5)
print(arr)

[43.41393772 27.59809212 33.57705043 91.09936551 30.6373413 ]


11. Using np.logspace()

In [19]:
arr = np.logspace(1, 3, 5)

print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [20]:
arr = np.eye(5)[2]

print(arr)

[0. 0. 1. 0. 0.]


12. Using np.eye()

In [22]:
arr=np.eye(4)[2]
print(arr)

[0. 0. 1. 0.]


#2. 2D-Array

In [23]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(arr.shape)

(3, 3)


In [25]:
print(arr.ndim)

2


In [26]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(3, 3)
9
int64


2. Using np.zeros()

In [27]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. Using np.ones()

In [28]:
arr=np.ones((3,4))
print(arr
      )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Using np.full()

In [29]:
arr = np.full((3,4),100)

print(arr)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


6. Using np.arange() + reshape()

In [30]:
arr = np.arange(1,13).reshape(3,4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
arr=np.arange(2,14)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


7. Using np.linspace() + reshape()

In [32]:
arr = np.linspace(10,100,12).reshape(3,4)

print(arr)

[[ 10.          18.18181818  26.36363636  34.54545455]
 [ 42.72727273  50.90909091  59.09090909  67.27272727]
 [ 75.45454545  83.63636364  91.81818182 100.        ]]


8.Using np.identity()

In [33]:
arr = np.identity(5)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Accessing Elements

In [34]:
arr=np.array([
    [10,20,30,40],
    [40,50,60,70],
    [70,80,90,100]
])

In [35]:
print(arr)

[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]


In [36]:
print(arr.shape)

(3, 4)


In [37]:
print(arr.ndim)

2


In [38]:
print(arr[1])

[40 50 60 70]


In [39]:
print(arr[1,2])

60


In [40]:
print(arr[-1,-1])

100


In [41]:
print(arr[:2])

[[10 20 30 40]
 [40 50 60 70]]


In [42]:
print(arr[:2])

[[10 20 30 40]
 [40 50 60 70]]


In [43]:
print(arr[:2])

[[10 20 30 40]
 [40 50 60 70]]


In [44]:
print(arr[1,:])

[40 50 60 70]


#3. Operations on 2D-Array




In [45]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[10 20 30]
 [40 50 60]]

Matrix B:
[[1 2 3]
 [4 5 6]]


In [46]:
c=A*B
print(c)

[[ 10  40  90]
 [160 250 360]]


In [47]:
c=A+B
print(c)

[[11 22 33]
 [44 55 66]]


In [48]:
c=A-B
print(c)

[[ 9 18 27]
 [36 45 54]]


In [50]:
c=A/B
print(c)

[[10. 10. 10.]
 [10. 10. 10.]]


In [51]:
result = A // B

print(result)

[[10 10 10]
 [10 10 10]]


In [52]:
result = A % B

print(result)

[[0 0 0]
 [0 0 0]]


In [53]:
result = A ** 2

print(result)

[[ 100  400  900]
 [1600 2500 3600]]


In [54]:
result = np.sqrt(A)

print(result)

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [56]:
result = np.cbrt(A)

print(result)

[[2.15443469 2.71441762 3.10723251]
 [3.41995189 3.6840315  3.91486764]]


In [58]:
print(np.max(A))

60


In [59]:
print(np.min(B))

1


In [60]:
print(np.sum(A))

210


In [61]:
print(np.mean(B))

3.5


In [62]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

result = A @ B

print(result)

[[19 22]
 [43 50]]


 Transpose

In [63]:
print(A.T)

[[1 3]
 [2 4]]


In [64]:
print(B.T)

[[5 7]
 [6 8]]


In [65]:
print(A.flatten())

[1 2 3 4]


In [66]:
A = np.array([
    [5,2,8],
    [7,1,3]
])

print(np.sort(A))

[[2 5 8]
 [1 3 7]]


#Arthmetic Operations

In [67]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [69]:
print("a + b=",a+b)
print("a - b=",a-b)
print("a * b=",a*b)
print("a / b=",a/b)

a + b= [5 7 9]
a - b= [-3 -3 -3]
a * b= [ 4 10 18]
a / b= [0.25 0.4  0.5 ]


2. Scalar Operations

In [71]:
arr=np.array([7,8,5,7,9])
print("arr + 5=",arr+5)
print("arr - 5=",arr-5)
print("arr * 5=",arr*5)
print("arr / 5=",arr/5)

arr + 5= [12 13 10 12 14]
arr - 5= [2 3 0 2 4]
arr * 5= [35 40 25 35 45]
arr / 5= [1.4 1.6 1.  1.4 1.8]


3.Aggregation Functions

In [72]:
arr=np.array([7,8,5,7,9])
print("arr.max()=",arr.max())
print("arr.min()=",arr.min())
print("arr.sum()=",arr.sum())
print("arr.mean()=",arr.mean())

arr.max()= 9
arr.min()= 5
arr.sum()= 36
arr.mean()= 7.2


4.Statistical Functions

In [73]:
arr=np.array([7,8,5,7,9])
print("arr.std()=",arr.std())
print("arr.var()=",arr.var())
print("arr.cumsum()=",arr.cumsum())
print("arr.cumprod=",arr.cumprod())

arr.std()= 1.32664991614216
arr.var()= 1.7600000000000002
arr.cumsum()= [ 7 15 20 27 36]
arr.cumprod= [    7    56   280  1960 17640]


#Axis wise operations

In [74]:
x=np.array([[4,7,8,9,10],
            [8,7,9,5,40]])
print(x)



[[ 4  7  8  9 10]
 [ 8  7  9  5 40]]


In [75]:
print("Sum of each column (axis=0)",np.sum(x,axis=0))
print("Sum of each row (axis=1)",np.sum(x,axis=1))
print("Mean of each column (axis=0)",np.mean(x,axis=0))
print("Mean of each row (axis=1)",np.mean(x,axis=1))
print("Max of each column (axis=0)",np.max(x,axis=0))
print("Max of each row (axis=1)",np.max(x,axis=1))


Sum of each column (axis=0) [12 14 17 14 50]
Sum of each row (axis=1) [38 69]
Mean of each column (axis=0) [ 6.   7.   8.5  7.  25. ]
Mean of each row (axis=1) [ 7.6 13.8]
Max of each column (axis=0) [ 8  7  9  9 40]
Max of each row (axis=1) [10 40]


#3.Program: Student Subject-wise Marks

In [77]:
import numpy as np

# Subject-wise marks of 5 students (5 subjects)
marks = np.array([
    [85, 90, 78, 88, 92],   # Student 1
    [76, 81, 69, 73, 80],   # Student 2
    [95, 91, 89, 94, 90],   # Student 3
    [65, 70, 72, 68, 75],   # Student 4
    [88, 84, 86, 90, 87]    # Student 5
])

# Student names
students = ["Aaliya Fatma", "Shadmani Noor", "Ummehain Noor", "Zainab fatma", "Talat"]

# Subject names
subjects = ["Math", "Science", "English", "Computer", "Physics"]

print("Student Marks Matrix:\n")
print(marks)



# Total marks of each student
total = np.sum(marks, axis=1)

# Average marks of each student
average = np.mean(marks, axis=1)

# Percentage of each student
# Assuming each subject is out of 100
percentage = (total / (marks.shape[1] * 100)) * 100

# -------------------------------
# Display Result
# -------------------------------

print("\nStudent Result\n")
print("-" * 70)

for i in range(len(students)):
    print(f"Student : {students[i]}")
    print("Marks   :", marks[i])
    print(f"Total   : {total[i]}")
    print(f"Average : {average[i]:.2f}")
    print(f"Percent : {percentage[i]:.2f}%")
    print("-" * 70)

Student Marks Matrix:

[[85 90 78 88 92]
 [76 81 69 73 80]
 [95 91 89 94 90]
 [65 70 72 68 75]
 [88 84 86 90 87]]

Student Result

----------------------------------------------------------------------
Student : Aaliya Fatma
Marks   : [85 90 78 88 92]
Total   : 433
Average : 86.60
Percent : 86.60%
----------------------------------------------------------------------
Student : Shadmani Noor
Marks   : [76 81 69 73 80]
Total   : 379
Average : 75.80
Percent : 75.80%
----------------------------------------------------------------------
Student : Ummehain Noor
Marks   : [95 91 89 94 90]
Total   : 459
Average : 91.80
Percent : 91.80%
----------------------------------------------------------------------
Student : Zainab fatma
Marks   : [65 70 72 68 75]
Total   : 350
Average : 70.00
Percent : 70.00%
----------------------------------------------------------------------
Student : Talat
Marks   : [88 84 86 90 87]
Total   : 435
Average : 87.00
Percent : 87.00%
----------------------------------

#4.Program with User Input

In [80]:
import numpy as np

students = int(input("Enter the number of students: "))
subjects = int(input("Enter the number of subjects: "))

# Store student names
student_names = []

for i in range(students):
    name = input(f"Enter name of Student {i+1}: ")
    student_names.append(name)

marks = np.zeros((students, subjects), dtype=int)

# Input marks
for i in range(students):
    print(f"\nEnter marks for {student_names[i]}")

    for j in range(subjects):
        marks[i][j] = int(input(f"Subject {j+1}: "))

# Calculations
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
percentage = (total / (subjects * 100)) * 100

# Display Results
print("\nRESULT")
print("=" * 60)

for i in range(students):
    print(f"Student Name : {student_names[i]}")
    print("Marks        :", marks[i])
    print("Total        :", total[i])
    print("Average      :", round(average[i], 2))
    print("Percentage   :", round(percentage[i], 2), "%")
    print("-" * 60)

Enter the number of students: 2
Enter the number of subjects: 2
Enter name of Student 1: Aaliya Fatma
Enter name of Student 2: Faisal Sheikh

Enter marks for Aaliya Fatma
Subject 1: 98
Subject 2: 87

Enter marks for Faisal Sheikh
Subject 1: 89
Subject 2: 75

RESULT
Student Name : Aaliya Fatma
Marks        : [98 87]
Total        : 185
Average      : 92.5
Percentage   : 92.5 %
------------------------------------------------------------
Student Name : Faisal Sheikh
Marks        : [89 75]
Total        : 164
Average      : 82.0
Percentage   : 82.0 %
------------------------------------------------------------
