<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/Practise_Day_6(Numpy_Universal_Functions).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. np.add()

In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

result=np.add(arr1,arr2)
print(result)

[ 7  9 11 13 15]


#2. np.subtract()

In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

result=np.subtract(arr1,arr2)
print(result)

[-5 -5 -5 -5 -5]


#3. np.multiply()

In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

result=np.multiply(arr1,arr2)
print(result)

[ 6 14 24 36 50]


#4. np.divide()

In [4]:
import numpy as np

a = np.array([20,40,60])
b = np.array([2,4,5])

print(np.divide(a,b))

[10. 10. 12.]


#5. np.mod()

In [5]:
import numpy as np

a = np.array([10,15,20])
b = np.array([3,4,6])

print(np.mod(a,b))

[1 3 2]


#6. np.power()

In [6]:
import numpy as np

a = np.array([2,3,4])

print(np.power(a,2))

[ 4  9 16]


#7.np.sqrt()

In [8]:
import numpy as np

a = np.array([4,9,16,25])

print(np.sqrt(a))

[2. 3. 4. 5.]


#8.np.square()

In [9]:
import numpy as np

a = np.array([2,3,4,5])

print(np.square(a))

[ 4  9 16 25]


#9.np.log()

In [10]:
import numpy as np

a = np.array([2,3,4,5])

print(np.log(a))

[0.69314718 1.09861229 1.38629436 1.60943791]


#10.np.sin()

In [11]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
