<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/Practise_Day_3(Reshaping_Arrays_in_Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Create a 1D Array

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


#2. Reshape 1D Array to 2D

In [5]:
new_arr=arr.reshape(2,3)
print(new_arr)


[[1 2 3]
 [4 5 6]]


#3. Reshape into 3 Rows and 2 Columns

In [6]:
new_arr2=arr.reshape(3,2)
print(new_arr2)

[[1 2]
 [3 4]
 [5 6]]


#4. Check Shape After Reshaping

In [7]:
arr.shape

(6,)

In [9]:
new_arr.shape

(2, 3)

In [10]:
new_arr2.shape

(3, 2)

#5. Reshape into 3D Array

In [11]:
arr=np.array([1,2,3,4,5,6,7,8])
new_arr3=arr.reshape(2,2,2)
print(new_arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#6. Using -1 in Reshape

In [12]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

new_arr=arr.reshape(2,-1)

print(new_arr)

[[1 2 3]
 [4 5 6]]


#7. Flatten a 2D Array using reshape()

In [14]:
ARR=np.array([[1,2,3],
              [4,5,6]])

NEW_ARR=ARR.reshape(-1)

print(NEW_ARR)

[1 2 3 4 5 6]


#8. Flatten using ravel()

In [15]:
import numpy as np

arr=np.array([[1,2,3],
              [4,5,6]])

print(arr.ravel())

[1 2 3 4 5 6]


#Difference Between flatten() and ravel()

In [16]:
import numpy as np

arr=np.array([[1,2],[3,4]])

flat=arr.flatten()
rav=arr.ravel()

flat[0]=100
rav[1]=200

print(arr)
print(flat)
print(rav)

[[  1 200]
 [  3   4]]
[100   2   3   4]
[  1 200   3   4]


 #9. Transpose a Matrix

In [17]:
arr=np.array([[1,2,3],
              [4,5,6]])

print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


#. Resize an Array

In [18]:
import numpy as np

arr=np.array([1,2,3,4])

arr.resize((2,2))

print(arr)

[[1 2]
 [3 4]]


# Reshape a 12-Element Array

In [19]:
import numpy as np

arr=np.arange(1,13)

print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
