<a href="https://colab.research.google.com/github/faisu6339-glitch/Machine-learning/blob/main/Practise_Day_5(Numpy_Splitting_Arrays).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Split 1D Array into Equal Parts

In [1]:
import numpy as np

In [6]:
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,3)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


#2. Split into 2 Equal Parts

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

result = np.split(arr,2)

print(result)

[array([1, 2, 3]), array([4, 5, 6])]


#3. Split at Specific Index

In [4]:
arr=np.array([10,20,30,40,50,60])
result=np.split(arr,[2,4])
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


#4. Split at Multiple Indices

In [9]:
import numpy as np

arr = np.array([5,10,15,20,25,30,35])

result = np.split(arr,[1,3,6])

print(result)

[array([5]), array([10, 15]), array([20, 25, 30]), array([35])]


#5. array_split() (Unequal Splitting)

In [10]:
import numpy as np

arr = np.array([1,2,3,4,5])

result = np.array_split(arr,3)

print(result)

[array([1, 2]), array([3, 4]), array([5])]


#6.Horizontal Split (hsplit)

In [14]:
arr1=np.array([[10,20,30,40,50,60],
              [70,80,90,100,110,120]])
result=np.hsplit(arr1,2)
print(result)

[array([[10, 20, 30],
       [70, 80, 90]]), array([[ 40,  50,  60],
       [100, 110, 120]])]


#7.Horizontal Split into 4 Parts

In [15]:
import numpy as np

arr=np.array([[10,20,30,40],
              [50,60,70,80]])

result=np.hsplit(arr,4)

print(result)

[array([[10],
       [50]]), array([[20],
       [60]]), array([[30],
       [70]]), array([[40],
       [80]])]


#8.Vertical Split (vsplit)

In [17]:
import numpy as np

arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

result=np.vsplit(arr,2)

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


#9.Vertical Split into 4 Parts

In [18]:
import numpy as np

arr=np.array([[10,20],
              [30,40],
              [50,60],
              [70,80]])

result=np.vsplit(arr,4)

print(result)

[array([[10, 20]]), array([[30, 40]]), array([[50, 60]]), array([[70, 80]])]


#10.Split 3D Array using dsplit()

In [19]:
import numpy as np

arr=np.arange(24).reshape(2,3,4)

result=np.dsplit(arr,2)

print(result)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


#11.Split Rows using axis=0

In [20]:
import numpy as np

arr=np.arange(24).reshape(6,4)

result=np.array_split(arr,3,axis=0)

print(result)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


#12.Split Columns using axis=1

In [21]:
import numpy as np

arr=np.arange(20).reshape(4,5)

result=np.array_split(arr,2,axis=1)

print(result)

[array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])]


#13.Access Particular Split

In [22]:
import numpy as np
arr=np.arange(15)
parts=np.array_split(arr,3)
print(parts)
print(parts[0])
print(parts[1])
print(parts[2])


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


#14.Split and Find Sum of Each Part

In [23]:
arr=np.arange(12)

parts=np.array_split(arr,3)

for part in parts:
    print(part)
    print(np.sum(part))

[0 1 2 3]
6
[4 5 6 7]
22
[ 8  9 10 11]
38


#15.. Split and Find Maximum

In [24]:
arr=np.arange(12)

parts=np.array_split(arr,3)

for part in parts:
    print(part)
    print(np.max(part))

[0 1 2 3]
3
[4 5 6 7]
7
[ 8  9 10 11]
11


#16.Split and Find Mean

In [26]:
arr=np.arange(12)

parts=np.array_split(arr,3)

for part in parts:
    print(part)
    print(np.mean(part))

[0 1 2 3]
1.5
[4 5 6 7]
5.5
[ 8  9 10 11]
9.5


#17.Split and Find min

In [25]:
arr=np.arange(12)

parts=np.array_split(arr,3)

for part in parts:
    print(part)
    print(np.min(part))

[0 1 2 3]
0
[4 5 6 7]
4
[ 8  9 10 11]
8


#18.Split Matrix at Given Columns

In [27]:
import numpy as np

arr=np.arange(20).reshape(4,5)

result=np.split(arr,[2,4],axis=1)

print(result)

[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]]), array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18]]), array([[ 4],
       [ 9],
       [14],
       [19]])]
